server:
  port: 8080
spring:
  application:
      name: orderonline
  datasource:
      url: jdbc:mysql://localhost:3306/orderonline?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      cache: false
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  jackson:
    default-property-inclusion: non_null
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
      use-generated-keys: true
      use-column-label: true
      map-underscore-to-camel-case: true
    type-aliases-package: com.liziwei.orderonline.entity
